# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e6677108a3a767c23bf71d47730cd0a0270bc5a0dc4eafe52a8ef8af436f2cc558a8296fb73c6ad42af147102e93a7bcf55f4d5864fc8fc6420e3b775dbd3dd

test:
  secret_key_base: ed7f63e336d9b01dc2cf946ed6cbb5d1fac96cceac8cb3ad7be977d2cedae69071b1c05d16890a8d2ac0761abb9231be1e3dd35e6304a936e67ae88f3f6df483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
